name: trigger-build

on:
  workflow_dispatch:
  push:
    branches-ignore:    
      - 'main'

jobs:
  call:
    uses: nerethos/docker_build-workflows/.github/workflows/docker-build.yml@main
    secrets: inherit
